#version 450
#include "common.glsl"
layout(local_size_x = 256) in;
layout(std430, binding = 1) buffer Parts { Particle parts[]; };
layout(std430, binding = 2) readonly buffer Counters { uint counters[]; };
layout(push_constant) uniform PC { ivec4 a; vec4 b; } pc;

void main() {
    uint i = GID_U;
    if (i >= min(counters[pc.a.x], uint(pc.a.y))) {
        return;
    }
    parts[i].pos.xyz += pc.b.xyz;
}
