#version 450
#include "common.glsl"
layout(local_size_x = 256) in;
layout(std430, binding = 1) readonly buffer Src { Particle src[]; };
layout(std430, binding = 2) readonly buffer SrcCounters { uint srcCounters[]; };
layout(std430, binding = 3) writeonly buffer Dst { Particle dst[]; };
layout(std430, binding = 4) buffer DstCounters { uint dstCounters[]; };
layout(push_constant) uniform PC { ivec4 a; vec4 b; } pc;

void main() {
    uint i = GID_U;
    if (i >= srcCounters[pc.a.x]) {
        return;
    }
    Particle p = src[i];
    if (p.pos.w < 0.0 && p.vel.w == 0.0) {
        return;
    }
    uint o = atomicAdd(dstCounters[pc.a.y], 1u);
    if (o < uint(pc.a.z)) {
        p.pos.xyz += pc.b.xyz;
        dst[o] = p;
    }
}
