#version 450
#include "common.glsl"
layout(local_size_x = 256) in;
layout(std430, binding = 1) buffer Parts { Particle parts[]; };
layout(std430, binding = 2) readonly buffer Counters { uint counters[]; };
layout(push_constant) uniform PC { ivec4 a; ivec4 b; } pc;

void main() {
    uint i = GID_U;
    if (i >= counters[pc.a.x]) {
        return;
    }
    vec3 x = parts[i].pos.xyz;
    for (int k = 0; k < G.removeInfo.x; k++) {
        if (all(greaterThanEqual(x, G.removeBox[2 * k].xyz)) && all(lessThan(x, G.removeBox[2 * k + 1].xyz))) {
            parts[i].pos.w = -1.0;
            return;
        }
    }
}
